apiVersion: apps/v1
kind: Deployment
metadata:
  name: dice-game-deployment
  labels:
    app: dice-game
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: dice-game
  template:
    metadata:
      labels:
        app: dice-game
    spec:
      containers:
      - name: dice-game
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 80
