apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dice-game-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: dice-game.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dice-game
                port:
                  number: 80
