apiVersion: v1
kind: Service
metadata:
  name: dice-game
  labels:
    app: dice-game
spec:
  type: {{ .Values.service.type }}
  selector:
    app: dice-game
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
