apiVersion: v1
kind: Service
metadata:
  name: dice-game
spec:
  type: {{ .Values.service.type }} # Ensure this is NodePort for your testing
  selector:
    app: dice-game
  ports:
    - port: {{ .Values.service.port }} # External port (e.g., 80)
      targetPort: 8080                # Internal container port
      protocol: TCP